### ISSUE TITLE
Cloudflare Workers

### ISSUE THREAD

**Issue by mertushka** [jakjus/serverless-discord-bot#1]
You can use Cloudflare Workers, it's much better.

[Article](https://discord.com/developers/docs/tutorials/hosting-on-cloudflare-workers)

**Comment by jakjus** [comment]
Why is it better though? Isn't it architecturally the same thing? :) 

On top of that, provided article implements a serverless anti-pattern, which is a lambda monolith (serverless function monolith). My solution is built mainly to avoid that and it is described further in my [Medium Article](https://betterprogramming.pub/serverless-discord-bot-on-aws-in-5-steps-956dca04d899) :)

Interesting source, though!

**Comment by mertushka** [comment]
I didn't know what you mentioned as I have never used AWS before, I read your article and now I understand the logic. As for the Cloudflare Workers part, it has really amazing performance and it has very useful features. 

However, you have done a good project, I am closing the issue with my advice :)
