### ISSUE TITLE
Error on INTERACTIONS ENDPOINT URL

### ISSUE THREAD

**Issue by GoulartNogueira** [jakjus/serverless-discord-bot#2]
Invalid lambda response received: Invalid API Gateway Response Keys: {'trace', 'errorType', 'errorMessage'} in {'errorType': 'TypeError', 'errorMessage': 'The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined', 'trace': ['TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined', '    at new NodeError (internal/errors.js:322:7)', '    at Function.from (buffer.js:334:9)', '    at Runtime.exports.handler (/var/task/src/modules/proxy-function.js:16:14)', '    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)']}

**Comment by GoulartNogueira** [comment]
Digging deeper, I realized Discord is using uppercase characters on the headers.
```
X-Signature-Ed25519
X-Signature-Timestamp
```

**Comment by GoulartNogueira** [comment]
This will solve the issue:

proxy-function.js
```
    const signature = event.headers['x-signature-ed25519'] || event.headers['X-Signature-Ed25519'];
    const timestamp = event.headers['x-signature-timestamp'] || event.headers['X-Signature-Timestamp'];

```

**Comment by jakjus** [comment]
Thanks a lot, merged 😊
