### ISSUE TITLE
[ Question ] Sharding

### ISSUE THREAD

**Issue by McDefault** [jakjus/serverless-discord-bot#7]
Hi there,

Hope you are having a good day.

I have no experience in using Discord for AWS so I wonder about how sharding would work in this scenario. How would this work if you have 3000+ guilds on your bot, meaning you would be forced to use sharding?

**Comment by jakjus** [comment]
hey. sharding is not necessary in this scenario. there is no running node process (listener) instance.

every request is treated individually with a different lambda call with infinite scaling.

thats where this approach benefits! you'll not be forced to use sharding on 3000+ guilds.
